/**
 * optimistic.ninja posts API
 * Posts API for optimistic.ninja
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: j@optimistic.ninja
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreatePostRequest from './model/CreatePostRequest';
import ListPostsResponse from './model/ListPostsResponse';
import Post from './model/Post';
import PostAllOf from './model/PostAllOf';
import PostSummary from './model/PostSummary';
import PostUpdateMask from './model/PostUpdateMask';
import UpdatePostRequest from './model/UpdatePostRequest';
import PostsApi from './api/PostsApi';


/**
* Posts_API_for_optimistic_ninja.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var @OptimisticninjaPostsApiJsClient = require('index'); // See note below*.
* var xxxSvc = new @OptimisticninjaPostsApiJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new @OptimisticninjaPostsApiJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new @OptimisticninjaPostsApiJsClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new @OptimisticninjaPostsApiJsClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1-SNAPSHOT
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreatePostRequest model constructor.
     * @property {module:model/CreatePostRequest}
     */
    CreatePostRequest,

    /**
     * The ListPostsResponse model constructor.
     * @property {module:model/ListPostsResponse}
     */
    ListPostsResponse,

    /**
     * The Post model constructor.
     * @property {module:model/Post}
     */
    Post,

    /**
     * The PostAllOf model constructor.
     * @property {module:model/PostAllOf}
     */
    PostAllOf,

    /**
     * The PostSummary model constructor.
     * @property {module:model/PostSummary}
     */
    PostSummary,

    /**
     * The PostUpdateMask model constructor.
     * @property {module:model/PostUpdateMask}
     */
    PostUpdateMask,

    /**
     * The UpdatePostRequest model constructor.
     * @property {module:model/UpdatePostRequest}
     */
    UpdatePostRequest,

    /**
    * The PostsApi service constructor.
    * @property {module:api/PostsApi}
    */
    PostsApi
};
