version: '3'

services:
  postgres13:
    image: postgres:13.4
    env_file:
      - docker/postgres/postgres.env
    ports:
      - 5432:5432

  pgadmin:
    build:
      dockerfile: Dockerfile
      context: docker/pgadmin
    env_file:
      - docker/pgadmin/pgadmin.env
    ports:
      - 8484:80