/**
 * optimistic.ninja posts API
 * Posts API for optimistic.ninja
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: j@optimistic.ninja
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.@OptimisticninjaPostsApiJsClient);
  }
}(this, function(expect, @OptimisticninjaPostsApiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new @OptimisticninjaPostsApiJsClient.ListPostsResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListPostsResponse', function() {
    it('should create an instance of ListPostsResponse', function() {
      // uncomment below and update the code to test ListPostsResponse
      //var instance = new @OptimisticninjaPostsApiJsClient.ListPostsResponse();
      //expect(instance).to.be.a(@OptimisticninjaPostsApiJsClient.ListPostsResponse);
    });

    it('should have the property postSummaries (base name: "postSummaries")', function() {
      // uncomment below and update the code to test the property postSummaries
      //var instance = new @OptimisticninjaPostsApiJsClient.ListPostsResponse();
      //expect(instance).to.be();
    });

    it('should have the property nextPage (base name: "nextPage")', function() {
      // uncomment below and update the code to test the property nextPage
      //var instance = new @OptimisticninjaPostsApiJsClient.ListPostsResponse();
      //expect(instance).to.be();
    });

    it('should have the property pageCount (base name: "pageCount")', function() {
      // uncomment below and update the code to test the property pageCount
      //var instance = new @OptimisticninjaPostsApiJsClient.ListPostsResponse();
      //expect(instance).to.be();
    });

  });

}));
