/**
 * optimistic.ninja posts API
 * Posts API for optimistic.ninja
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: j@optimistic.ninja
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreatePostRequest model module.
 * @module model/CreatePostRequest
 * @version 0.0.1-SNAPSHOT
 */
class CreatePostRequest {
    /**
     * Constructs a new <code>CreatePostRequest</code>.
     * @alias module:model/CreatePostRequest
     * @param title {String} post title
     * @param summary {String} post summary
     * @param markdown {String} post markdown
     * @param imageUrl {String} image url
     */
    constructor(title, summary, markdown, imageUrl) { 
        
        CreatePostRequest.initialize(this, title, summary, markdown, imageUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, summary, markdown, imageUrl) { 
        obj['title'] = title;
        obj['summary'] = summary;
        obj['markdown'] = markdown;
        obj['imageUrl'] = imageUrl;
    }

    /**
     * Constructs a <code>CreatePostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePostRequest} obj Optional instance to populate.
     * @return {module:model/CreatePostRequest} The populated <code>CreatePostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePostRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('markdown')) {
                obj['markdown'] = ApiClient.convertToType(data['markdown'], 'String');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
        }
        return obj;
    }


}

/**
 * post title
 * @member {String} title
 */
CreatePostRequest.prototype['title'] = undefined;

/**
 * post summary
 * @member {String} summary
 */
CreatePostRequest.prototype['summary'] = undefined;

/**
 * post markdown
 * @member {String} markdown
 */
CreatePostRequest.prototype['markdown'] = undefined;

/**
 * image url
 * @member {String} imageUrl
 */
CreatePostRequest.prototype['imageUrl'] = undefined;






export default CreatePostRequest;

