/**
 * optimistic.ninja posts API
 * Posts API for optimistic.ninja
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: j@optimistic.ninja
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostSummary model module.
 * @module model/PostSummary
 * @version 0.0.1-SNAPSHOT
 */
class PostSummary {
    /**
     * Constructs a new <code>PostSummary</code>.
     * @alias module:model/PostSummary
     */
    constructor() { 
        
        PostSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostSummary} obj Optional instance to populate.
     * @return {module:model/PostSummary} The populated <code>PostSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostSummary();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
        }
        return obj;
    }


}

/**
 * post id
 * @member {String} id
 */
PostSummary.prototype['id'] = undefined;

/**
 * post title
 * @member {String} title
 */
PostSummary.prototype['title'] = undefined;

/**
 * post summary
 * @member {String} summary
 */
PostSummary.prototype['summary'] = undefined;

/**
 * image url
 * @member {String} imageUrl
 */
PostSummary.prototype['imageUrl'] = undefined;






export default PostSummary;

