/**
 * optimistic.ninja posts API
 * Posts API for optimistic.ninja
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: j@optimistic.ninja
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PostUpdateMask.
* @enum {}
* @readonly
*/
export default class PostUpdateMask {
    
        /**
         * value: "TITLE"
         * @const
         */
        "TITLE" = "TITLE";

    
        /**
         * value: "SUMMARY"
         * @const
         */
        "SUMMARY" = "SUMMARY";

    
        /**
         * value: "MARKDOWN"
         * @const
         */
        "MARKDOWN" = "MARKDOWN";

    
        /**
         * value: "IMAGE_URL"
         * @const
         */
        "IMAGE_URL" = "IMAGE_URL";

    

    /**
    * Returns a <code>PostUpdateMask</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PostUpdateMask} The enum <code>PostUpdateMask</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

