/**
 * optimistic.ninja posts API
 * Posts API for optimistic.ninja
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: j@optimistic.ninja
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostAllOf model module.
 * @module model/PostAllOf
 * @version 0.0.1-SNAPSHOT
 */
class PostAllOf {
    /**
     * Constructs a new <code>PostAllOf</code>.
     * @alias module:model/PostAllOf
     * @param authorId {String} author id
     * @param created {Date} date-time of post creation
     * @param updated {Date} date-time of last post update
     * @param markdown {String} post markdown
     */
    constructor(authorId, created, updated, markdown) { 
        
        PostAllOf.initialize(this, authorId, created, updated, markdown);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, authorId, created, updated, markdown) { 
        obj['authorId'] = authorId;
        obj['created'] = created;
        obj['updated'] = updated;
        obj['markdown'] = markdown;
    }

    /**
     * Constructs a <code>PostAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAllOf} obj Optional instance to populate.
     * @return {module:model/PostAllOf} The populated <code>PostAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAllOf();

            if (data.hasOwnProperty('authorId')) {
                obj['authorId'] = ApiClient.convertToType(data['authorId'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Date');
            }
            if (data.hasOwnProperty('markdown')) {
                obj['markdown'] = ApiClient.convertToType(data['markdown'], 'String');
            }
        }
        return obj;
    }


}

/**
 * author id
 * @member {String} authorId
 */
PostAllOf.prototype['authorId'] = undefined;

/**
 * date-time of post creation
 * @member {Date} created
 */
PostAllOf.prototype['created'] = undefined;

/**
 * date-time of last post update
 * @member {Date} updated
 */
PostAllOf.prototype['updated'] = undefined;

/**
 * post markdown
 * @member {String} markdown
 */
PostAllOf.prototype['markdown'] = undefined;






export default PostAllOf;

